[package]
name = "problem006"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4"
num-bigint = "0.4.3"
num-traits = "0.2.15"
num-iter = "0.1.43"