/*
   The sequence of triangle numbers is generated by adding the natural
   numbers. So the 7^th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 =
   28. The first ten terms would be:

                    1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

   Let us list the factors of the first seven triangle numbers:

      1: 1
      3: 1,3
      6: 1,2,3,6
     10: 1,2,5,10
     15: 1,3,5,15
     21: 1,3,7,21
     28: 1,2,4,7,14,28

   We can see that 28 is the first triangle number to have over five
   divisors.

   What is the value of the first triangle number to have over five hundred
   divisors?

*/



fn tri_num(k:u64) -> u64 {
    k*(k+1)/2
}

fn count_divisors(k:u64) -> u64 {
    let mut j = 1;
    let mut divisors = 0;
    while j*j < k {
        if k % j == 0 {
            divisors += 1;
        }
        j += 1;
    }
    divisors * 2
}



fn main() {
    let mut k = 1;
    loop {
        let tri_k = tri_num(k);
        let divs_k = count_divisors(tri_k);
        if divs_k > 500 {
            println!("{} : {} - {} divisors", k, tri_k, divs_k);
            break;
        }
        k += 1;
    }


    //for i in 1..8 {
    //    let tri_i = tri_num(i);
    //    println!("{} : {} - {} divisors", i, tri_i, count_divisors(tri_i));
    //}
}
